version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus_config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - service-network
  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - "3000:3000"
    volumes:
      - service-volume:/var/lib/grafana
    networks:
      - service-network

networks:
  service-network:

volumes:
  service-volume:
